Working on setting up scenario deployment for dino diner.

diff --git a/lib/Taskfile.yml b/lib/Taskfile.yml
--- a/lib/Taskfile.yml
+++ b/lib/Taskfile.yml
@@ -3,13 +3,42 @@ version: '3'
 ######################################################################################
 #  Utility Functions to be reused by other task files.
 ######################################################################################
-
+  
 tasks:
+  waitForEbpfConnection:
+    silent: true
+    cmds:
+      - |
+        {{.OBSERVE_FUNCTIONS}}
+        if [ -z "{{.STQL}}" ]; then
+          echo "STQL required."
+          exit 1
+        fi
+        count=0
+        timeout=360 
+        echo "Waiting for ebpf connection to component '{{.COMPONENT}}'"
+        while true
+        do
+          found=$(find_ebpf_connection {{.STS_URL}} {{.STS_TOKEN}} "{{.STQL}}" "{{.COMPONENT}}")
+          if [ "$found" == "found" ]; then
+            echo "Ebpf connection to component established"
+            break
+          fi
+          printf "Current: '$found'\r"
+          {{.ELAPSED_TIMER}}  
+        done
+    requires:
+      vars: [STS_TOKEN, STS_TOKEN, STQL, COMPONENT]
+
   waitForHealthState:
     silent: true
     cmds:
       - |
         {{.OBSERVE_FUNCTIONS}}
+        if [ -z "{{.STQL}}" ]; then
+          echo "STQL required."
+          exit 1
+        fi
         count=0
         timeout=360 
         echo "Waiting for component to reach a '{{.STATE}}' state"
@@ -21,18 +50,10 @@ tasks:
             break
           fi
           printf "Current: '$state'\r"
-          count=$(($count + 10))
-          if [ $count -gt $timeout ]; then
-            echo "Wait timed out!!!"
-            exit 1
-          fi
-          timer=10
-          while [ $timer -gt -1 ]; do
-            printf "\rElapsed: %02ds. Retry: %02ds. " $(($count - 10)) $timer
-            timer=$(($timer - 1))
-            sleep 1
-          done
+          {{.ELAPSED_TIMER}} 
         done
+    requires:
+      vars: [STS_TOKEN, STS_TOKEN, STQL, STATE]
 
   countdown:
     silent: true
@@ -41,24 +62,54 @@ tasks:
       - |
         {{.FUNCTIONS}} 
         countdown "{{.TIME}}"
+    requires:
+      vars: [TIME]
 
 vars:
+  ELAPSED_TIMER: |
+    count=$(($count + 10))
+    if [ $count -gt $timeout ]; then
+      echo "Wait timed out!!!"
+      exit 1
+    fi
+    timer=10
+    while [ $timer -gt -1 ]; do
+      printf "\rElapsed: %02ds. Retry: %02ds. " $(($count - 10)) $timer
+      timer=$(($timer - 1))
+      sleep 1
+    done
+
   OBSERVE_FUNCTIONS: |
+    find_ebpf_connection() {
+        local url=$1
+        local service_token=$2
+        local stql=$3
+        local componentName=$4
+        local result
+        local found
+        result=$(get_snapshot $url $service_token "$stql" "true")
+        echo $result > last_ebpf_conn_server_resp.txt
+        found=$(echo $result | jq -r "if .viewSnapshotResponse.components[] | select(.name == \"$componentName\") then \"found\" else \"not-found\" end")
+        echo $found
+    }
+
     get_component_state() {
         local url=$1
         local service_token=$2
         local stql=$3
 
-        local component
-        component=$(get_component_snapshot $url $service_token "$stql")
-        echo $component > last_server_resp.txt
-        echo $component | jq -r '.viewSnapshotResponse.components[0].state.healthState'
+        local result
+        echo $stql > last_server_resp.txt
+        result=$(get_snapshot $url $service_token "$stql" "false")
+        echo $result >> last_server_resp.txt
+        echo $result | jq -r '.viewSnapshotResponse.components[0].state.healthState'
     }
 
-    get_component_snapshot() {
+    get_snapshot() {
       local url=$1
       local service_token=$2
       local stql=$3
+      local connectedComponents=$4
 
       local req
       req=$(cat <<EOM
@@ -72,7 +123,7 @@ vars:
         "groupedByDomain":       false,
         "groupedByRelation":     false,
         "autoGrouping":          false,
-        "connectedComponents":   false,
+        "connectedComponents":   $connectedComponents,
         "neighboringComponents": false,
         "showFullComponent":     false
       }
